config/routes.rb
Ebilling::Application.routes.draw do
  devise_for :users

  root 'dashboard#index'

  resources :e_bills do
    member do
      get :pre_trigger
      put :trigger
      put :proces, as: :process
      put :send_receipt
      put :send_invoice
      get :export
    end
  end
  get "/diagnostic", controller: "diagnostic", action: "index"
  get "/locale/:locale", controller: "locale", action: "update", as: :locale
  resources :audit_trails, only: [:index, :show]
  resources :profiles
  resources :users do 
    resource :fee_strategy
  end
  resource  :settings
  resource  :system_configs do
    collection do
      post :regenerate_stats 
    end
  end
  resources :countries
  resource  :e_bill_exports
  resource  :shared_keys
  resources :batch_files, only: [:new, :create, :index]
  resource :outline, controller: :outline, only: [:edit, :update, :show] do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :mobiles
  resources :mobile_traces
  resources :monthly_stats
  resources :currencies do 
    resources :fee_buckets
  end
  resources :ebilling_payment_accounts
  resources :merchant_payment_system_mappings
  resources :anonymous_searches, only: [:new, :create]
  
  resources :payment_system_operator_merchants, only: [:index]
  resources :merchant_payment_systems, only: [:index]

  namespace :merchant do 
    resources :registrations, only: [:new, :create]
  end

  namespace :api do
    scope '/v:api_version' do
      namespace :mobileapp do
        resources :mobiles do 
          member do 
            put :verify
            put :forget_pin
          end
        end

        resources :mobile_traces
        resources :e_bills, only: [:create] do 
          collection do 
            get :search
            get :history
            get :by_external_reference
            get :download_receipt
          end
        end
      end
    end

    namespace :v1 do
      namespace :merchant do
        resources :e_bills do
          member do
            put :send, action: :trigger
            put :process, action: :handle
          end
          collection do 
            post :bulk_create
          end
        end
      end

      namespace :payment_gateway do
        resources :e_bills do
          member do
            put :pay
            put :verify
          end
        end
      end
    end
  end

  post 'soap_ebills/:id/update' => 'soap_ebills#update'
  post 'soap_ebills/:id/verify' => 'soap_ebills#verify'

end

app/models/ebilling_payment_account.rb
# == Schema Information
#
# Table name: ebilling_payment_accounts
#
#  id                :integer          not null, primary key
#  payment_system_id :integer
#  payment_id        :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#

class EbillingPaymentAccount < ActiveRecord::Base

  belongs_to :payment_system, class_name: 'User'

  validates :payment_id, presence: true
  validates :payment_system_id, uniqueness: true, presence: true
  validate  :payment_system_must_have_specific_role

  private

    def payment_system_must_have_specific_role
      return unless payment_system.present?

      unless payment_system.has_profile?(Profile::PAYMENT_SYSTEM)
        errors.add(:payment_system_id, 'payment system does not have specific role')
      end
    end
end

app/controllers/ebilling_payment_accounts_controller.rb
class EbillingPaymentAccountsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_authorization

  def index
    @ebilling_payment_accounts = EbillingPaymentAccount.includes(:payment_system).all
  end

  def new
    @ebilling_payment_account = EbillingPaymentAccount.new
  end

  def create
    @ebilling_payment_account = EbillingPaymentAccount.new(ebilling_payment_account_params)
    if @ebilling_payment_account.save
      flash[:notice] = "EBilling Payment Account created for #{@ebilling_payment_account.payment_system.username}"
      redirect_to ebilling_payment_accounts_url
    else
      render 'new'
    end
  end

  def edit
    @ebilling_payment_account = EbillingPaymentAccount.find params[:id]
  end

  def update
    @ebilling_payment_account = EbillingPaymentAccount.find params[:id]
    if @ebilling_payment_account.update_attributes(ebilling_payment_account_params)
      flash[:notice] = "EBilling Payment Account created for #{@ebilling_payment_account.payment_system.username}"
      redirect_to ebilling_payment_accounts_url
    else
      render 'edit'
    end
  end

  def destroy
    @ebilling_payment_account = EbillingPaymentAccount.find params[:id]
    @ebilling_payment_account.destroy
    flash[:notice] = "EBilling Payment Account deleted for #{@ebilling_payment_account.payment_system.username}"
    redirect_to ebilling_payment_accounts_url
  end

  private

    def ebilling_payment_account_params
      params.require(:ebilling_payment_account).permit(:payment_system_id, :payment_id)
    end

    def check_authorization
      authorize! :manage, EbillingPaymentAccount
    end
end

app/helpers/ebilling_payment_accounts_helper.rb
module EbillingPaymentAccountsHelper
end

app/views/ebilling_payment_accounts/_ebilling_payment_account.html.erb
<tr class="<%= cycle('odd', 'even') -%>" id="ebilling-payment-account-row-<%= ebilling_payment_account.id -%>">
  <td class="center"><%= ebilling_payment_account.payment_system.username -%></td>
  <td class="center">
    <%= ebilling_payment_account.payment_id %>
  </td>
  <td>
    <%if can? :edit, ebilling_payment_account %>
      <%= link_to edit_ebilling_payment_account_path(ebilling_payment_account),  class: "btn btn-success" do -%>
          <i class="icon-eye icon-white"></i> <%= t "actions.edit" -%>
        <% end -%>
    <% end %>
    <%if can? :destroy, ebilling_payment_account %>
      <%= link_to ebilling_payment_account_path(ebilling_payment_account),  method: :delete, class: "btn btn-warning", confirm: 'Confirm to delete?' do -%>
          <i class="icon-trash icon-white"></i> <%= t "actions.delete" -%>
        <% end -%>
    <% end %>
  </td>
</tr>

app/views/ebilling_payment_accounts/_form.html.erb
<%= form_for @ebilling_payment_account, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>

    <div class="control-group <%= @ebilling_payment_account.errors[:payment_system_id].empty? ? '' : 'error' -%>">
      <%= f.label :payment_system, t("ebilling_payment_accounts.index.payment_system"), class: 'control-label' %>
      <div class="controls">
        <%= f.select :payment_system_id, User.payment_systems.collect { |u| [u.username, u.id] }, {}, 
          { :disabled => !@ebilling_payment_account.new_record? } %>
        <% @ebilling_payment_account.errors[:payment_system_id].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="control-group <%= @ebilling_payment_account.errors[:payment_id].empty? ? '' : 'error' -%>">
      <%= f.label :payment_id, t("ebilling_payment_accounts.index.payment_id"), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :payment_id %>
        <% @ebilling_payment_account.errors[:payment_id].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t("actions.save_changes"),  class: "btn btn-primary" %>
      <%= link_to t("actions.cancel"), ebilling_payment_accounts_path, class: 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/ebilling_payment_accounts/edit.html.erb
<legend><%= t "ebilling_payment_accounts.index.edit_ebilling_payment_account" -%></legend>
<%= render 'form' -%>

app/views/ebilling_payment_accounts/index.html.erb
<legend>
  <div class="row-fluid">
    <div class="pull-right">
      <% if can?(:create, EbillingPaymentAccount) -%>
        <%= link_to new_ebilling_payment_account_path,  class: "btn btn-success" do -%>
          <i class="icon-plus icon-white"></i> <%= t "ebilling_payment_accounts.index.new_ebilling_payment_account" -%>
        <% end %>
      <% end -%>
    </div>
  </div>
</legend>

<div class="table-container">
  <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable">
    <thead>
      <tr role="row">
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 350px;"><%= t "ebilling_payment_accounts.index.payment_system" -%></th>
        <th role="columnheader" tabindex="0"><%= t "ebilling_payment_accounts.index.payment_id" -%></th>
        <th role="columnheader" tabindex="0" style="width: 300px;"><%= t "ebilling_payment_accounts.index.actions" -%></th>
      </tr>
    </thead>
    <tbody role="alert" aria-live="polite" aria-relevant="all">
      <%= render @ebilling_payment_accounts -%>
    </tbody>
  </table>
</div>

app/views/ebilling_payment_accounts/new.html.erb
<legend><%= t "ebilling_payment_accounts.index.new_ebilling_payment_account" -%></legend>
<%= render 'form' -%>