config/routes.rb
Ebilling::Application.routes.draw do
  devise_for :users

  root 'dashboard#index'

  resources :e_bills do
    member do
      get :pre_trigger
      put :trigger
      put :proces, as: :process
      put :send_receipt
      put :send_invoice
      get :export
    end
  end
  get "/diagnostic", controller: "diagnostic", action: "index"
  get "/locale/:locale", controller: "locale", action: "update", as: :locale
  resources :audit_trails, only: [:index, :show]
  resources :profiles
  resources :users do 
    resource :fee_strategy
  end
  resource  :settings
  resource  :system_configs do
    collection do
      post :regenerate_stats 
    end
  end
  resources :countries
  resource  :e_bill_exports
  resource  :shared_keys
  resources :batch_files, only: [:new, :create, :index]
  resource :outline, controller: :outline, only: [:edit, :update, :show] do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :mobiles
  resources :mobile_traces
  resources :monthly_stats
  resources :currencies do 
    resources :fee_buckets
  end
  resources :ebilling_payment_accounts
  resources :merchant_payment_system_mappings
  resources :anonymous_searches, only: [:new, :create]
  
  resources :payment_system_operator_merchants, only: [:index]
  resources :merchant_payment_systems, only: [:index]

  namespace :merchant do 
    resources :registrations, only: [:new, :create]
  end

  namespace :api do
    scope '/v:api_version' do
      namespace :mobileapp do
        resources :mobiles do 
          member do 
            put :verify
            put :forget_pin
          end
        end

        resources :mobile_traces
        resources :e_bills, only: [:create] do 
          collection do 
            get :search
            get :history
            get :by_external_reference
            get :download_receipt
          end
        end
      end
    end

    namespace :v1 do
      namespace :merchant do
        resources :e_bills do
          member do
            put :send, action: :trigger
            put :process, action: :handle
          end
          collection do 
            post :bulk_create
          end
        end
      end

      namespace :payment_gateway do
        resources :e_bills do
          member do
            put :pay
            put :verify
          end
        end
      end
    end
  end

  post 'soap_ebills/:id/update' => 'soap_ebills#update'
  post 'soap_ebills/:id/verify' => 'soap_ebills#verify'

end

app/models/currency.rb
# == Schema Information
#
# Table name: currencies
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Currency < ActiveRecord::Base

  validates :code, uniqueness: true, presence: true,
    format: { with: /\A[a-zA-Z]{3}\z/, message: "Not valid currency" }

  has_many :fee_buckets

end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController

  before_action :authenticate_user!
  before_action :check_authorization

  def index
    @currencies = Currency.all.order('code')
  end

  def new
    @currency = Currency.new
  end

  def create
    @currency = Currency.new(currency_params)
    if @currency.save
      flash[:notice] = "Currency #{@currency.code} is created"
      redirect_to currencies_url
    else
      render 'new'
    end
  end
  
  private

    def currency_params
      params.require(:currency).permit(:code)
    end

    def check_authorization
      authorize! :manage, Currency
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_currency.html.erb
<tr class="<%= cycle('odd', 'even') -%>" id="currency-row-<%= currency.id -%>">
  <td class="center"><%= currency.code -%></td>
  <td class="center">
    <div>
      <% currency.fee_buckets.order('min_transactions').each do |fee_bucket| %>
        <div style="margin-bottom: 3px;">
          <div class="span3">
            Min Transactions: <%= fee_bucket.min_transactions %>
          </div>
          <div class="span3">
            Max Transactions: <%= fee_bucket.max_transactions %>
          </div>
          <div class="span3">
            Fee Value: <%= fee_bucket.fee_value %>
          </div>
          <div class="span3">
            <%= link_to edit_currency_fee_bucket_path(currency, fee_bucket), class: 'btn btn-primary' do %>
              <i class="icon-edit icon-white"></i>
            <% end %>
            <%= link_to currency_fee_bucket_path(currency, fee_bucket), method: :delete, class: 'btn btn-danger', confirm: 'Confirm to delete?' do %>
              <i class="icon-remove icon-white"></i>
            <% end %>
          </div>
          <div class="clear"></div>
        </div>
      <% end %>
    </div>
  </td>
  <td>
    <%if can? :edit, currency %>
      <%= link_to new_currency_fee_bucket_path(currency.id),  class: "btn btn-success" do -%>
          <i class="icon-eye icon-white"></i> <%= t "actions.create_fee_bucket" -%>
        <% end -%>
    <% end %>
  </td>
</tr>

app/views/currencies/index.html.erb
<legend>
  <div class="row-fluid">
    <div class="pull-right">
      <% if can?(:create, Currency) -%>
        <%= link_to new_currency_path,  class: "btn btn-success" do -%>
          <i class="icon-plus icon-white"></i> <%= t "currencies.index.new_currency" -%>
        <% end %>
      <% end -%>
    </div>
  </div>
</legend>

<div class="table-container">
  <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable">
    <thead>
      <tr role="row">
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 50px;"><%= t "currencies.index.code" -%></th>
        <th role="columnheader" tabindex="0"><%= t "currencies.index.fee_buckets" -%></th>
        <th role="columnheader" tabindex="0" style="width: 300px;"><%= t "currencies.index.actions" -%></th>
      </tr>
    </thead>
    <tbody role="alert" aria-live="polite" aria-relevant="all">
      <%= render @currencies -%>
    </tbody>
  </table>
</div>

app/views/currencies/new.html.erb
<%= form_for @currency, url: currencies_path, html: { class: 'form-horizontal strategy-form' } do |f| %>
  <fieldset>

    <div class="control-group<%= @currency.errors[:code].empty? ? '' : ' error' -%>">
      <%= f.label :code, class: 'control-label' do -%>
        <%= t "currency.form.code" -%><span class="text-error">(*)</span>
      <% end -%>
      <div class="controls">
        <%= f.select :code, currency_options, {}, class: 'span5' %>
        <% @currency.errors[:code].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t("actions.save_changes"),  class: "btn btn-primary" %>
      <%= link_to t("actions.cancel"), currencies_path, class: 'btn' %>
    </div>
  </fieldset>
<% end %>