config/routes.rb
Ebilling::Application.routes.draw do
  devise_for :users

  root 'dashboard#index'

  resources :e_bills do
    member do
      get :pre_trigger
      put :trigger
      put :proces, as: :process
      put :send_receipt
      put :send_invoice
      get :export
    end
  end
  get "/diagnostic", controller: "diagnostic", action: "index"
  get "/locale/:locale", controller: "locale", action: "update", as: :locale
  resources :audit_trails, only: [:index, :show]
  resources :profiles
  resources :users do 
    resource :fee_strategy
  end
  resource  :settings
  resource  :system_configs do
    collection do
      post :regenerate_stats 
    end
  end
  resources :countries
  resource  :e_bill_exports
  resource  :shared_keys
  resources :batch_files, only: [:new, :create, :index]
  resource :outline, controller: :outline, only: [:edit, :update, :show] do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :mobiles
  resources :mobile_traces
  resources :monthly_stats
  resources :currencies do 
    resources :fee_buckets
  end
  resources :ebilling_payment_accounts
  resources :merchant_payment_system_mappings
  resources :anonymous_searches, only: [:new, :create]
  
  resources :payment_system_operator_merchants, only: [:index]
  resources :merchant_payment_systems, only: [:index]

  namespace :merchant do 
    resources :registrations, only: [:new, :create]
  end

  namespace :api do
    scope '/v:api_version' do
      namespace :mobileapp do
        resources :mobiles do 
          member do 
            put :verify
            put :forget_pin
          end
        end

        resources :mobile_traces
        resources :e_bills, only: [:create] do 
          collection do 
            get :search
            get :history
            get :by_external_reference
            get :download_receipt
          end
        end
      end
    end

    namespace :v1 do
      namespace :merchant do
        resources :e_bills do
          member do
            put :send, action: :trigger
            put :process, action: :handle
          end
          collection do 
            post :bulk_create
          end
        end
      end

      namespace :payment_gateway do
        resources :e_bills do
          member do
            put :pay
            put :verify
          end
        end
      end
    end
  end

  post 'soap_ebills/:id/update' => 'soap_ebills#update'
  post 'soap_ebills/:id/verify' => 'soap_ebills#verify'

end

app/models/batch_file.rb
# == Schema Information
#
# Table name: batch_files
#
#  id          :integer          not null, primary key
#  file        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  state       :string(255)
#  provisioned :integer          default(0)
#  succeeded   :integer          default(0)
#  failed      :integer          default(0)
#

class BatchFile < ActiveRecord::Base


  #  Hash for parameters to be extracted from excel file
  KEY_MAPPINGS = {:merchant_name_m => :username,
                    :payer_msisdn_m => :payer_msisdn, :amount_m => :amount,
                    :short_description_m => :short_description, 
                    :payer_name_o => :payer_name, :payer_address_o => :payer_address,
                    :payer_city_o => :payer_city, 
                    :expiration_date_o => :expire_at, :external_reference_o => :merchant_internal_ref,
                    :payer_email_m => :payer_email, :description_o => :description, 
                    :accept_partial_payment_o => :accept_partial_payment,
                    :minimum_amount_o => :minimum_amount,
                    :payer_id_o => :payer_id,
                    :payer_code_o => :payer_code,
                    :email_o => :email,
                    :sms_o => :sms,
                    :due_date_o => :due_date,
                    :additional_info_o => :additional_info,
                    :data0_o => :data0,
                    :data1_o => :data1,
                    :data2_o => :data2,
                    :data3_o => :data3,
                    :data4_o => :data4,
                    :data5_o => :data5,
                    :data6_o => :data6,
                    :data7_o => :data7,
                    :data8_o => :data8,
                    :data9_o => :data9
                     };


  #  Mounts the given uploader on the given column. 
  #  This means that assigning and reading from the column will upload and retrieve files.
  mount_uploader :file, FileUploader

  #  Specifies a one-to-one association with user class.
  belongs_to :user

  #  Specifies a one-to-many association with ebills class
  has_many :e_bills

  #  State machine for start and finish events for provision state
  state_machine initial: :created do
    event :start do
      transition :created => :in_process
    end

    event :finish do
      transition :in_process => :finished
    end
  end

  #  Increments succeeded and provisioned count by 1
  def inc_succeeded
    self.succeeded += 1
    self.provisioned += 1
  end

  #  Increments failed and provisioned count by 1 
  def inc_failed
    self.failed += 1
    self.provisioned +=1
  end


  #  1. Checks if user has permission to provision the file 
  #  2. Start 
  #  3. Keeps old provisioned number
  #  4. Initiates provisioned count to 0
  #  5. Initiates excel to nil
  #  6. Checks extension of current file, and initiates a roo object on the current file  
  #  7. Returns back if excel is still nil
  #  8. Reads the last column number to get column count
  #  9. Defines two arrays to hold names of columns and converted names of columns to match database column names 
  #  10. Iterates over column names and stores them 
  #  11. Gets number of rows and scans rows one by one to prepare ebill if rows are greater than 1 in number
  #  12. Saves ebill if provision is correct, else shows error message 
  #  13. Saves every 100 provisions  
  def provision

    unless user.can_provision?
      logger.error("The user can't provision. #{user}")
      return
    end
    start
    logger.info("Begin provision #{file.current_path}")

    old_provisioned = provisioned # keep old provisioned number
    provisioned_count = 0

    excel = nil
    if file.current_path.ends_with? ".xlsx"
      excel = Roo::Excelx.new(file.current_path)
    elsif file.current_path.ends_with? ".xls"
      excel = Roo::Excel.new(file.current_path)
    end

    unless excel
      finish
      return
    end

    # Read header
    column_count = excel.last_column

    header = []
    original_header = []
    1.upto(column_count) do |column|
      column_name = excel.cell(1, column)
      header << KEY_MAPPINGS[column_name.delete(" ").downcase.to_sym]
      original_header << column_name
    end
    last_row = excel.last_row
    if last_row > 1
      2.upto(last_row) do |row|       # start from the second row
        attributes = {}
        # original attributes is just for audit trail
        original_attributes = {}

        1.upto(column_count) do |column|
          value = excel.cell(row, column)
          if value.class == Float
            value = value.to_i.to_s
          end
          attributes[header[column - 1]] = value
          original_attributes[original_header[column - 1]] = value
          if(user.has_profile? Profile::MERCHANT)
            attributes.merge(username: user.username)
          end
        end
        e_bill = e_bills.build attributes
        e_bill.params = original_attributes
        e_bill.operator = self.user.username

        if e_bill.create true
          inc_succeeded
        else
          logger.error("provision not correct: #{e_bill.errors.full_messages}")
          e_bills.delete e_bill
          inc_failed
        end

        # save every 100 provision
        provisioned_count += 1
        if provisioned_count % 100 == 0
          save
        end
      end
    end

    save
    logger.debug("batch file valid: #{errors.full_messages}")
    logger.info("finish batch file #{file}")
    finish
  end


end

app/controllers/batch_files_controller.rb
class BatchFilesController < ApplicationController

  before_filter :authenticate_user!
  #  1. Creates a new batch file model
  def new
    @batch_file = BatchFile.new
  end

  #  1. Creates a new batch files model with params filtered
  #  2. Saves batch file model in database 
  #  3. If save is successful, it creates a delay job to call action provision
  #  4. Flashes a notice which says that the file is provisioned in background
  #  5. Redirects to batch files view with html format
  #  6. If save fails, then new is rendered
  def create
    @batch_file = current_user.batch_files.new create_batch_file_params

    if @batch_file.save
      @batch_file.delay.provision
      flash[:notice] = I18n.t("batch_files.notice.provisioned_in_background")
      respond_to do |format|
        format.html { redirect_to batch_files_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.js
      end

    end
  end

  #  1. Fetches all batch files accessible by current user and pagintes them 20 per page
  #  2. Returns those records with page number requested
  def index
    @batch_files = BatchFile.order("created_at desc")
                      .accessible_by(current_ability)
                      .paginate(:page => params[:page], :per_page => 10)
  end

  private
  
  #  1. Filters request params to have only file parameter
  def create_batch_file_params
    params.require(:batch_file).permit(:file)
  end

end

app/helpers/batch_files_helper.rb
module BatchFilesHelper
end

app/views/batch_files/_batch_file.html.erb
<tr class="<%= cycle('odd', 'even') -%>" id="batch-file-row-<%= batch_file.id -%>">
  <td class="center"><%= File.basename(batch_file.file.current_path) -%></td>
  <td><%= batch_file.created_at.to_s(:db)  -%></td>
  <td class="center"><%= batch_file.state -%></td>
  <td class="center"><%= batch_file.provisioned -%></td>
  <td class="center"><%= batch_file.succeeded -%></td>
  <td class="center"><%= batch_file.failed -%></td>
  <td class="center">
    <%= link_to t("batch_files.index.view_ebills"), e_bills_path(batch_file_id: batch_file.id), class: "btn btn-success" -%>
  </td>
</tr>

app/views/batch_files/create.js.erb
<%# encoding: utf-8 %>
<% if @batch_file.new_record? %>
  alert('<%= t "batch_files.upload_error" -%>')
<% else %>
  window.location = '<%= "#{batch_files_path}" -%>'
<% end %>

app/views/batch_files/index.html.erb
<legend>
  <div class="pull-right">
    <% if can? :read, BatchFile -%>
      <%= link_to batch_files_path,  class: "btn btn-success" do -%>
         <%= t "batch_files.index.refresh" -%>
      <% end %>
    <% end -%>

    <% if can? :create, BatchFile -%>
      <%= link_to new_batch_file_path,  class: "btn btn-warning", id: 'batch-provision' do -%>
        <i class="icon-plus icon-white"></i> <%= t "batch_files.index.batch_provisioning" -%>
      <% end %>
    <% end -%>

    <%= link_to '/Facture.xlsx',  class: "btn btn-warning", id: 'batch-template' do -%>
      <%= t "batch_files.index.download_batch_template" -%>
    <% end %>
  </div>

  <div class="row-fluid">
    <%= t "batch_files.index.all" -%>
  </div>
</legend>

<div class="table-container">
  <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable">
    <thead>
      <tr role="row">
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 120px;"><%= t "batch_files.index.batch_file" -%></th>
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 120px;"><%= t "batch_files.index.uploaded_at" -%></th>
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 120px;"><%= t "batch_files.index.state" -%></th>
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 60px;"><%= t "batch_files.index.total_provisioned" -%></th>
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 60px;"><%= t "batch_files.index.total_succeeded" -%></th>
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 60px;"><%= t "batch_files.index.total_failed" -%></th>
        <th class="sorting_asc" role="columnheader" tabindex="0" style="width: 60px;"><%= t "batch_files.index.actions" -%></th>
      </tr>
    </thead>
    <tbody role="alert" aria-live="polite" aria-relevant="all">
      <%= render @batch_files -%>
    </tbody>
  </table>
</div>

app/views/batch_files/new.html.erb
<legend><%= t "batch_files.index.batch_provisioning" -%></legend>
<%= form_for @batch_file, html: { class: 'form-horizontal' } do |f| -%>
  <fieldset>

    <div class="control-group<%= @batch_file.errors[:file].empty? ? '' : ' error' %>">
      <%= f.label :file, class: 'control-label' do -%>
        <%= t "batch_files.new.select_file" -%>
      <% end -%>
      <div class="controls">
        <span class="btn btn-success fileinput-button">
          <i class="glyphicon glyphicon-plus"></i>
          <span><%= t "batch_files.new.select_file" -%>...</span>
          <!-- The file input field used as target for the file upload widget -->
          <%= f.file_field :file, class: 'file-upload' %>
        </span>

        <!-- The global progress bar -->
        <div id="progress" class="progress">
          <div class="progress-bar progress-bar-success"></div>
        </div>
      </div>
    </div>

  </fieldset>
<% end -%>