config/routes.rb
Ebilling::Application.routes.draw do
  devise_for :users

  root 'dashboard#index'

  resources :e_bills do
    member do
      get :pre_trigger
      put :trigger
      put :proces, as: :process
      put :send_receipt
      put :send_invoice
      get :export
    end
  end
  get "/diagnostic", controller: "diagnostic", action: "index"
  get "/locale/:locale", controller: "locale", action: "update", as: :locale
  resources :audit_trails, only: [:index, :show]
  resources :profiles
  resources :users do 
    resource :fee_strategy
  end
  resource  :settings
  resource  :system_configs do
    collection do
      post :regenerate_stats 
    end
  end
  resources :countries
  resource  :e_bill_exports
  resource  :shared_keys
  resources :batch_files, only: [:new, :create, :index]
  resource :outline, controller: :outline, only: [:edit, :update, :show] do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :mobiles
  resources :mobile_traces
  resources :monthly_stats
  resources :currencies do 
    resources :fee_buckets
  end
  resources :ebilling_payment_accounts
  resources :merchant_payment_system_mappings
  resources :anonymous_searches, only: [:new, :create]
  
  resources :payment_system_operator_merchants, only: [:index]
  resources :merchant_payment_systems, only: [:index]

  namespace :merchant do 
    resources :registrations, only: [:new, :create]
  end

  namespace :api do
    scope '/v:api_version' do
      namespace :mobileapp do
        resources :mobiles do 
          member do 
            put :verify
            put :forget_pin
          end
        end

        resources :mobile_traces
        resources :e_bills, only: [:create] do 
          collection do 
            get :search
            get :history
            get :by_external_reference
            get :download_receipt
          end
        end
      end
    end

    namespace :v1 do
      namespace :merchant do
        resources :e_bills do
          member do
            put :send, action: :trigger
            put :process, action: :handle
          end
          collection do 
            post :bulk_create
          end
        end
      end

      namespace :payment_gateway do
        resources :e_bills do
          member do
            put :pay
            put :verify
          end
        end
      end
    end
  end

  post 'soap_ebills/:id/update' => 'soap_ebills#update'
  post 'soap_ebills/:id/verify' => 'soap_ebills#verify'

end

app/models/merchant_payment_system_mapping.rb
# == Schema Information
#
# Table name: merchant_payment_system_mappings
#
#  id                  :integer          not null, primary key
#  merchant_id         :integer
#  payment_system_id   :integer
#  merchant_ps_id      :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  ps_percentage       :float            default(0.0)
#  search_field        :string(255)
#  ebilling_percentage :float            default(0.0)
#

class MerchantPaymentSystemMapping < ActiveRecord::Base

  belongs_to :merchant, class_name: 'User'
  belongs_to :payment_system, class_name: 'User'

  validates :merchant_id, presence: true
  validates :payment_system_id, presence: true
  validates_uniqueness_of :merchant_id, :scope => :payment_system_id

  validates :merchant_ps_id, presence: true #, uniqueness: true

  validate :merchant_should_have_merchant_profile
  validate :payment_system_should_have_payment_system_profile

  include Searchable
  searchable :merchant_name, :payment_system_name, :merchant_ps_id

  def merchant_name
    self.merchant.username
  end

  def payment_system_name
    self.payment_system.username
  end

  def total_percentage
    ps_percentage + ebilling_percentage
  end

  private

    def merchant_should_have_merchant_profile
      if merchant && !merchant.has_profile?(Profile::MERCHANT)
        errors.add(:merchant_id, 'should have merchant profile')
      end
    end

    def payment_system_should_have_payment_system_profile
      if payment_system && !payment_system.has_profile?(Profile::PAYMENT_SYSTEM)
        errors.add(:payment_system_id, 'should have payment system profile')
      end
    end

    def store_search_field
      self.search_field = [merchant.try(:username), payment_system.try(:username), merchant_ps_id].map(&:downcase).join(' ')
    end
end

app/controllers/merchant_payment_system_mappings_controller.rb
class MerchantPaymentSystemMappingsController < ApplicationController

  #  1. Authenticates user before every action in this controller
  before_filter :authenticate_user!

  #  1. Retrieves and returns all mappings with params merchant and payment system
  def index
    @query = params[:query]
    @merchant_payment_system_mappings = MerchantPaymentSystemMapping.includes([:merchant, :payment_system])
    @merchant_payment_system_mappings = @merchant_payment_system_mappings.search(@query) unless @query.blank?
  end

  #  1. Checks if user has permission to create mapping
  #  2. Returns empty new model for mapping
  def new
    authorize! :create, MerchantPaymentSystemMapping
    @merchant_payment_system_mapping = MerchantPaymentSystemMapping.new
  end

  #  1. Creates new mapping with filtered params 
  #  2. Checks permission to create 
  #  3. Saves the mapping
  #  4. If saved, message is shown else new page is rendered for mapping.
  def create
    @merchant_payment_system_mapping = MerchantPaymentSystemMapping.new(merchant_payment_system_mapping_params)
    authorize! :create, @merchant_payment_system_mapping


    if @merchant_payment_system_mapping.save
      flash[:notice] = "Merchant PaymentSystem mapping created. "
      redirect_to merchant_payment_system_mappings_url
    else
      render 'new'
    end
  end

  #  1. Finds mapping by id in request
  #  2. Checks if user has permission to update
  def edit
    @merchant_payment_system_mapping = MerchantPaymentSystemMapping.find(params[:id])
    authorize! :update, @merchant_payment_system_mapping
  end


  #  1. Finds mapping by id
  #  2. Checks permission to update
  #  3. Updates mapping with filtered params 
  #  4. Displays message
  #  5. Redirects to mappings url
  #  6. If mapping is not updated, redirects to edit page
  def update
    @merchant_payment_system_mapping = MerchantPaymentSystemMapping.find(params[:id])
    authorize! :update, @merchant_payment_system_mapping

    if @merchant_payment_system_mapping.update_attributes(merchant_payment_system_mapping_params)
      flash[:notice] = "Merchant PaymentSystem mapping updated. "
      redirect_to merchant_payment_system_mappings_url
    else
      render 'edit'
    end
  end


  #  1. Finds a mapping by id 
  #  2. Checks permission to delete
  #  3. Deletes the mapping 
  #  4. Shows message for the same
  #  5. Redirects to mappings url where mappings are shown
  def destroy
    @merchant_payment_system_mapping = MerchantPaymentSystemMapping.find(params[:id])
    authorize! :delete, @merchant_payment_system_mapping
    
    @merchant_payment_system_mapping.destroy
    flash[:notice] = "Merchant PaymentSystem mapping deleted. "
    redirect_to merchant_payment_system_mappings_url
  end

  private

    #  1. Filters request params the following way.
    def merchant_payment_system_mapping_params
      params.require(:merchant_payment_system_mapping).permit(:merchant_id, :payment_system_id,
        :merchant_ps_id, :ps_percentage, :ebilling_percentage)
    end
end

app/helpers/merchant_payment_system_mappings_helper.rb
module MerchantPaymentSystemMappingsHelper
end

app/views/merchant_payment_system_mappings/_form.html.erb
<%= form_for @merchant_payment_system_mapping, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>

    <div class="control-group <%= @merchant_payment_system_mapping.errors[:merchant_id].empty? ? '' : 'error' -%>">
      <%= f.label :merchant, t("merchant_payment_system_mappings.index.merchant"), class: 'control-label' %>
      <div class="controls">
        <%= f.select :merchant_id, User.merchants.collect { |u| [u.username, u.id] }, {}, 
          { :disabled => !@merchant_payment_system_mapping.new_record? } %>
        <% @merchant_payment_system_mapping.errors[:merchant_id].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="control-group <%= @merchant_payment_system_mapping.errors[:payment_system_id].empty? ? '' : 'error' -%>">
      <%= f.label :payment_system, t("merchant_payment_system_mappings.index.payment_system"), class: 'control-label' %>
      <div class="controls">
        <%= f.select :payment_system_id, User.payment_systems.collect { |u| [u.username, u.id] },
          {}, { :disabled => !@merchant_payment_system_mapping.new_record? } %>
        <% @merchant_payment_system_mapping.errors[:payment_system_id].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="control-group <%= @merchant_payment_system_mapping.errors[:merchant_ps_id].empty? ? '' : 'error' -%>">
      <%= f.label :merchant_ps_id, t("merchant_payment_system_mappings.index.merchant_ps_id"), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :merchant_ps_id %>
        <% @merchant_payment_system_mapping.errors[:merchant_ps_id].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="control-group <%= @merchant_payment_system_mapping.errors[:ps_percentage].empty? ? '' : 'error' -%>">
      <%= f.label :ps_percentage, t("merchant_payment_system_mappings.index.ps_percentage"), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :ps_percentage %>
        <% @merchant_payment_system_mapping.errors[:ps_percentage].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="control-group <%= @merchant_payment_system_mapping.errors[:ebilling_percentage].empty? ? '' : 'error' -%>">
      <%= f.label :ebilling_percentage, t("merchant_payment_system_mappings.index.ebilling_percentage"), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :ebilling_percentage %>
        <% @merchant_payment_system_mapping.errors[:ebilling_percentage].each do |error| -%>
          <span class="help-inline"><%= error -%></span>
        <% end -%>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t("actions.save_changes"),  class: "btn btn-primary" %>
      <%= link_to t("actions.cancel"), merchant_payment_system_mappings_path, class: 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/merchant_payment_system_mappings/_merchant_payment_system_mapping.html.erb
<tr class="<%= cycle('odd', 'even') -%>" id="mapping-row-<%= merchant_payment_system_mapping.id -%>">
  <td class="center"><%= merchant_payment_system_mapping.merchant.username -%></td>
  <td class="center"><%= merchant_payment_system_mapping.payment_system.username -%></td>
  <td class="center"><%= merchant_payment_system_mapping.merchant_ps_id -%></td>
  <td class="center"><%= number_to_percentage(merchant_payment_system_mapping.ps_percentage, precision: 2) -%></td>
  <td class="center"><%= number_to_percentage(merchant_payment_system_mapping.ebilling_percentage, precision: 2) -%></td>
  <td class="center"><%= number_to_percentage(merchant_payment_system_mapping.total_percentage, precision: 2) -%></td>
  <td class="center">
    <% if can?(:update, merchant_payment_system_mapping) -%>
      <%= link_to edit_merchant_payment_system_mapping_path(merchant_payment_system_mapping), class: "btn btn-warning" do -%>
          <i class="icon-trash icon-white"></i> <%= t "actions.edit" -%>
      <% end -%>
    <% end -%>

    <% if can?(:delete, merchant_payment_system_mapping) -%>
      <%= link_to merchant_payment_system_mapping_path(merchant_payment_system_mapping),  method: :delete, class: "btn btn-danger", confirm: t("merchant_payment_system_mapping.index.confirm_delete") do -%>
          <i class="icon-trash icon-white"></i> <%= t "actions.delete" -%>
      <% end -%>
    <% end -%>
  </td>
</tr>

app/views/merchant_payment_system_mappings/edit.html.erb
<legend><%= t "merchant_payment_system_mappings.index.edit_mapping" -%></legend>
<%= render 'form' -%>

app/views/merchant_payment_system_mappings/index.html.erb
<legend>
  <div class="row-fluid">
    <div class="pull-right">
      <% if can?(:create, User) -%>
        <%= link_to new_merchant_payment_system_mapping_path,  class: "btn btn-success" do -%>
          <i class="icon-plus icon-white"></i> <%= t "merchant_payment_system_mappings.index.new_mapping" -%>
        <% end %>
      <% end -%>
    </div>

    <%= render :partial => 'shared/search_form', :locals => { :path => merchant_payment_system_mappings_path } -%>
  </div>
</legend>

<div class="table-container">
  <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable">
    <thead>
      <tr role="row">
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.merchant" -%></th>
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.payment_system" -%></th>
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.merchant_ps_id" -%></th>
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.ps_percentage" -%></th>
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.ebilling_percentage" -%></th>
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.total_percentage" -%></th>
        <th role="columnheader" tabindex="0"><%= t "merchant_payment_system_mappings.index.actions" -%></th>
      </tr>
    </thead>
    <tbody role="alert" aria-live="polite" aria-relevant="all">
      <%= render @merchant_payment_system_mappings -%>
    </tbody>
  </table>
</div>

app/views/merchant_payment_system_mappings/new.html.erb
<legend><%= t "merchant_payment_system_mappings.index.new_mapping" -%></legend>
<%= render 'form' -%>